import type { Metadata } from "next";
import { Geist, Geist_Mono, Nunito } from "next/font/google";
import "./globals.css";
import { WagmiWrapper } from "@/providers/WagmiProvider";
import { Toaster } from "react-hot-toast";
import "@rainbow-me/rainbowkit/styles.css";


const nunito = Nunito({
  subsets: ["latin"],
  variable: "--font-nunito",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nunito.variable} ${nunito.variable} antialiased`}
      >
        <WagmiWrapper>
          {children}
          <Toaster position="top-right" />
        </WagmiWrapper>
      </body>
    </html>
  );
}
